#This file contains common configuration options for the two costmaps used in the navigation stack for more details on the parameters in this file, and a full list of the parameters used by the costmaps, please see http://www.ros.org/wiki/costmap_2d
map_type: voxel

origin_z: 0.0
z_resolution: 0.2
z_voxels: 10
unknown_threshold: 9
mark_threshold: 0

transform_tolerance: 0.5

obstacle_range: 2.5
max_obstacle_height: 2.0
raytrace_range: 3.0

footprint: [ [0.125, 0.125], [-0.125, 0.125], [-0.125, -0.125], [0.125, -0.125] ]
robot_radius: 0.25
footprint_padding: 0.01

inflation_radius: 0.3
cost_scaling_factor: 10.0

lethal_cost_threshold: 100

observation_sources: base_scan
base_scan: {data_type: LaserScan, expected_update_rate: 0.9,
  observation_persistence: 0.0, marking: true, clearing: true}
